apiVersion: v1
kind: Service
metadata:
  labels:
    app: news-backend
  name: news-backend
  #namespace: admin-che
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      #nodePort: 30000
  selector:
    app: news-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-backend
  #namespace: admin-che
  labels:
    app: news-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: news-backend
  template:
    metadata:
      labels:
        app: news-backend
    spec:
      containers:
        - env:
            - name: backend.nlp.url
              value: http://34.95.5.45:8080/function/hello-python
            - name: quarkus.datasource.jdbc.url
              value: jdbc:postgresql://postgis:5400/news?user=postgres&password=banane
          image: us.gcr.io/lab-project-one-368323/news-backend          #todo: replace <project_ID> with your actual project_ID 
          name: news-backend
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
  apiVersion: autoscaling/v1
  kind: HorizontalPodAutoscaler
  metadata:
    name: news-backend
  spec:
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: news-backend
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 50