apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgis
  name: postgis
  #namespace: admin-che
spec:
  #type: NodePort
  ports:
    - port: 5400
      targetPort: 5432
  selector:
    app: postgis
---
  apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: postgis-pv
  spec:
    capacity:
      storage: 5Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    storageClassName: slow
    hostPath:
      path: "/tmp/pgdata"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgis
  #namespace: admin-che
  labels:
    app: postgis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgis
  template:
    metadata:
      labels:
        app: postgis
    spec:
      containers:
        - env:
            - name: PGDATA
              value: /tmp/pgdata
            - name: POSTGRESQL_DATABASE
              value: news
            - name: POSTGRES_DB
              value: news
            - name: POSTGRES_PASSWORD
              value: banane
            - name: POSTGRES_USER
              value: postgres
          image: postgis/postgis
          name: postgis
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: "/tmp/pgdata"
              name: postgis-pv
      volumes:
        - name: postgis-pv